services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword